apiVersion: v1
kind: Service
metadata:
  name: cryptobackend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
  type: ClusterIP # Adjust the service type based on your needs
