apiVersion: v1
kind: Service
metadata:
  name: defi-frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Exposes the frontend service externally
