apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3 # You can adjust the number of replicas as needed for scaling
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: defi-frontend
          image: gcr.io/cryptotracker-393623/frontend:v1
          ports:
            - containerPort: 80
